<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('gallery_images', function (Blueprint $table) {
            $table->id();
            $table->string('filename')->comment('Unique filename generated by system');
            $table->string('original_name')->comment('Original filename from upload');
            $table->string('path', 500)->comment('Full path to image file');
            $table->string('thumbnail_path', 500)->comment('Full path to thumbnail file');
            $table->unsignedInteger('size')->comment('File size in bytes');
            $table->string('mime_type', 100)->comment('MIME type of the image');
            $table->string('alt_text')->nullable()->comment('Alt text for accessibility');
            $table->integer('display_order')->default(0)->comment('Display order (0 = first)');
            $table->boolean('is_active')->default(true)->comment('Active/inactive status');
            $table->timestamps();

            // Indexes for performance optimization
            $table->index(['is_active', 'display_order'], 'idx_active_order');
            $table->index('created_at', 'idx_created_at');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('gallery_images');
    }
};
